services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: inza124/main-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  blazor:
    image: inza124/main-blazor:latest
    container_name: blazor
    restart: always
    ports:
      - "5001:8080"
    depends_on:
      - backend
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      API_URL: http://backend:8080
      DEMO_API_URL: http://demo:8080

  demo:
    image: inza124/main-demo
    container_name: demo
    restart: always
    ports:
      - "5002:8080"
    depends_on:
      - blazor
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      LocalHost: http://host.docker.internal

volumes:
  mongo-data:
